AWSTemplateFormatVersion: "2010-09-09"
Description: "Create the CloudFront distribution for a static site - (v1.0.0)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  AcmCertificateArn:
    Type: "String"
    Description: "The ARN of the ACM Certificate."
  # DNS Entries
  PrimaryDnsEntryName:
    Type: "String"
    Description: "A primary friendly DNS CNAME for this distribution."
  SecondaryDnsEntryName:
    Type: "String"
    Description: "A secondary friendly DNS CNAME for this distribution."
    Default: "NONE"
  CloudFrontHostedZoneId:
    Type: "String"
    Description: "The CloudFront Hosted Zone ID.  This is a global value that should never change unless Amazon changes it."
    Default: "Z2FDTNDATAQYW2"
  # S3 Origin
  OriginAccessIdentity:
    Type: "String"
    Description: "The Amazon S3 origin access identity."
  # Default Origin
  DefaultOriginDomain:
    Type: "String"
    Description: "The default origin domain for this distribution."
  DefaultOriginId:
    Type: "String"
    Description: "The default ID for the primary domain."
    Default: "primary"
  # Distribution Configuration
  DefaultOriginPath:
    Type: "String"
    Description: "The default base path to retrieve files from at the origin."
    Default: "/content"
  DistributionComment:
    Type: "String"
    Description: "A comment to describe this distribution."
  DistributionEnabled:
    Type: "String"
    Description: "Should the distribution be enabled?"
    AllowedValues:
    - "true"
    - "false"
    Default: "true"
  DistributionIpv6Enabled:
    Type: "String"
    Description: "Enable IPv6 for this distribution."
    AllowedValues:
    - "true"
    - "false"
    Default: "true"
  DistributionHttpVersion:
    Type: "String"
    Description: "What is the latest version of the HTTP protocol which is allowed with this distribution?"
    AllowedValues:
    - "http1.1"
    - "http2"
    Default: "http2"
  DistributionDefaultRootObject:
    Type: "String"
    Description: "What is the default/index page which should be used for this CloudFront Distribution."
    Default: "index.html"
  Distribution404PagePath:
    Type: "String"
    Description: "What is the custom 404 page which should be used for this CloudFront Distribution."
    Default: "/404.html"
  DistributionAllowedMethods:
    Type: "CommaDelimitedList"
    Description: "A comma-delimited list of allowed methods: DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT"
    Default: "HEAD,GET,OPTIONS"
  DistributionCachedMethods:
    Type: "CommaDelimitedList"
    Description: "A comma-delimited list of cached methods.  The only methods that can be cached are: \"HEAD,GET\" or \"GET,HEAD,OPTIONS\""
    Default: "HEAD,GET,OPTIONS"
  DistributionCompress:
    Type: "String"
    Description: "Whether you want CloudFront to automatically compress certain files for this cache behavior."
    AllowedValues:
    - "true"
    - "false"
    Default: "true"
  DistributionSmoothStreaming:
    Type: "String"
    Description: "Indicates whether you want to distribute media files in the Microsoft Smooth Streaming format using the origin that is associated with this cache behavior."
    AllowedValues:
    - "true"
    - "false"
    Default: "false"
  # Default Cache Policy Configuration
  DefaultCachePolicyName:
    Type: "String"
    Description: "The name for the default cache policy.  This name must me unique within an account."
    AllowedPattern: "[a-zA-Z0-9_]+"
    Default: "default_static_site"
  DefaultCookieBehavior:
    Type: "String"
    Description: "Determines whether any cookies in viewer requests are included in the cache key and automatically included in requests that CloudFront sends to the origin."
    AllowedValues:
    - "none"
    - "whitelist"
    - "allExcept"
    - "all"
    Default: "none"
  DefaultEnableAcceptEncodingBrotli:
    Type: "String"
    Description: "A flag that can affect whether the Accept-Encoding HTTP header is included in the cache key and included in requests that CloudFront sends to the origin."
    AllowedValues:
    - "true"
    - "false"
    Default: "true"
  DefaultEnableAcceptEncodingGzip:
    Type: "String"
    Description: "A flag that can affect whether the Accept-Encoding HTTP header is included in the cache key and included in requests that CloudFront sends to the origin."
    AllowedValues:
    - "true"
    - "false"
    Default: "true"
  DefaultHeaderBehavior:
    Type: "String"
    Description: "Determines whether any HTTP headers are included in the cache key and automatically included in requests that CloudFront sends to the origin."
    AllowedValues:
    - "none"
    - "whitelist"
    Default: "none"
  DefaultQueryStringBehavior:
    Type: "String"
    Description: "Determines whether any URL query strings in viewer requests are included in the cache key and automatically included in requests that CloudFront sends to the origin."
    AllowedValues:
    - "none"
    - "whitelist"
    - "allExcept"
    - "all"
    Default: "none"
  # Distribution Caching TTL Defaults
  DistributionErrorCachingMinTtl:
    Type: "Number"
    Description: "The default error caching time-to-live for caching."
    Default: 60
  DistributionMinimumTtl:
    Type: "Number"
    Description: "The minimum time-to-live for caching."
    Default: 0
  DistributionMaximumTtl:
    Type: "Number"
    Description: "The maximum time-to-live for caching."
    Default: 31536000
  DistributionDefaultTtl:
    Type: "Number"
    Description: "The default time-to-live for caching."
    Default: 60
  DistributionViewerProtocolPolicy:
    Type: "String"
    Description: "Allow all protocols, redirect to HTTPS, or HTTPS only."
    AllowedValues:
    - "allow-all"
    - "redirect-to-https"
    - "https-only"
    Default: "redirect-to-https"
  DistributionPriceClass:
    Type: "String"
    AllowedValues:
    - "PriceClass_100"
    - "PriceClass_200"
    - "PriceClass_All"
    Default: "PriceClass_100"
  GeoRestrictionType:
    Type: "String"
    AllowedValues:
    - "blacklist"
    - "whitelist"
    - "none"
    Default: "none"
  # TODO: Check if TLS 1.3 is supported and probably upgrade to that.
  ViewerCertificateMinimumProtocolVersion:
    Type: "String"
    Description: "We recommend that you specify TLSv1.2_2021 unless your users are using browsers or devices that do not support TLSv1.1 or later."
    AllowedValues:
    - "SSLv3"
    - "TLSv1"
    - "TLSv1_2016"
    - "TLSv1.1_2016"
    - "TLSv1.2_2018"
    - "TLSv1.2_2019"
    - "TLSv1.2_2021"
    Default: "TLSv1.2_2021"
  ViewerCertificateSslSupportMethod:
    Type: "String"
    Description: "vip had a dedicated IP address (needed for older browsers), sni-only needs a fairly modern browser to work."
    AllowedValues:
    - "vip"
    - "sni-only"
    Default: "sni-only"
Conditions:
  DefaultOriginPath: !Not [ !Equals [ !Ref DefaultOriginPath, "" ] ]
  SecondaryDnsEntry: !Not [ !Equals [ !Ref SecondaryDnsEntryName, "NONE" ] ]
Resources:
  # NOTE: If creation of this resource fails with a strange error, it is probably because of a name collision.  Change the value for "DefaultCachePolicyName".
  DefaultCachePolicy:
    Type: "AWS::CloudFront::CachePolicy"
    Properties:
      CachePolicyConfig:
        Comment: "The default cache policy."
        DefaultTTL: !Ref DistributionDefaultTtl
        MaxTTL: !Ref DistributionMaximumTtl
        MinTTL: !Ref DistributionMinimumTtl
        Name: !Sub "${InfrastructureName}_${DefaultCachePolicyName}"
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: !Ref DefaultCookieBehavior
          EnableAcceptEncodingBrotli: !Ref DefaultEnableAcceptEncodingBrotli
          EnableAcceptEncodingGzip: !Ref DefaultEnableAcceptEncodingGzip
          HeadersConfig:
            HeaderBehavior: !Ref DefaultHeaderBehavior
          QueryStringsConfig:
            QueryStringBehavior: !Ref DefaultQueryStringBehavior
  Distribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
        - Ref: PrimaryDnsEntryName
        - !If [ SecondaryDnsEntry, !Ref SecondaryDnsEntryName, !Ref "AWS::NoValue" ]
        Comment: !Ref DistributionComment
        Origins:
        # Default Origin
        - DomainName: !Ref DefaultOriginDomain
          Id: !Ref DefaultOriginId
          OriginPath: !If [ DefaultOriginPath, !Ref DefaultOriginPath, !Ref "AWS::NoValue" ]
          S3OriginConfig:
            OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        Enabled: !Ref DistributionEnabled
        IPV6Enabled: !Ref DistributionIpv6Enabled
        HttpVersion: !Ref DistributionHttpVersion
        DefaultRootObject: !Ref DistributionDefaultRootObject
        DefaultCacheBehavior:
          AllowedMethods: !Ref DistributionAllowedMethods
          CachedMethods: !Ref DistributionCachedMethods
          CachePolicyId: !GetAtt DefaultCachePolicy.Id
          Compress: !Ref DistributionCompress
          SmoothStreaming: !Ref DistributionSmoothStreaming
          TargetOriginId: !Ref DefaultOriginId
          ViewerProtocolPolicy: !Ref DistributionViewerProtocolPolicy
        CustomErrorResponses:
        # NOTE: In CloudFront, we are only allowed to control the following error codes:
        # 400, 403, 404, 405, 414, 416, 500, 501, 502, 503, 504
        # Error codes that can be cached (per the HTTP standard) are:
        # 404, 405, 410, 501
        # See cache poisoning attack article: https://cpdos.org
        - ErrorCode: 404 # Not Found
          ErrorCachingMinTTL: !Ref DistributionErrorCachingMinTtl
          ResponseCode: 404
          ResponsePagePath: !Ref Distribution404PagePath
        - ErrorCode: 405 # Method Not Allowed
          ErrorCachingMinTTL: !Ref DistributionErrorCachingMinTtl
        - ErrorCode: 501 # Not Implemented
          ErrorCachingMinTTL: !Ref DistributionErrorCachingMinTtl
        # Error codes (that we control) which should never be cached (per the HTTP standard):
        - ErrorCode: 400 # Bad Request
          ErrorCachingMinTTL: 0
        - ErrorCode: 403 # Forbidden
          ErrorCachingMinTTL: 0
          ResponseCode: 404
          ResponsePagePath: !Ref Distribution404PagePath
        - ErrorCode: 414 # Request-URI Too Long
          ErrorCachingMinTTL: 0
        - ErrorCode: 416 # Requested Range Not Satisfiable
          ErrorCachingMinTTL: 0
        - ErrorCode: 500 # Internal Server Error
          ErrorCachingMinTTL: 0
        - ErrorCode: 502 # Bad Gateway
          ErrorCachingMinTTL: 0
        - ErrorCode: 503 # Service Unavailable
          ErrorCachingMinTTL: 0
        - ErrorCode: 504 # Gateway Timeout
          ErrorCachingMinTTL: 0
        PriceClass: !Ref DistributionPriceClass
        Restrictions:
          GeoRestriction:
            RestrictionType: !Ref GeoRestrictionType
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          MinimumProtocolVersion: !Ref ViewerCertificateMinimumProtocolVersion
          SslSupportMethod: !Ref ViewerCertificateSslSupportMethod
      Tags:
      - Key: "StackName"
        Value: !Ref "AWS::StackName"
  PrimaryDnsEntry:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:/route53/${InfrastructureName}/hosted-zone/id}}"
      Comment: "Primary CloudFront DNS \"A ALIAS\" entry."
      Name: !Ref PrimaryDnsEntryName
      Type: "A"
      AliasTarget:
        HostedZoneId: !Ref CloudFrontHostedZoneId
        DNSName: !GetAtt Distribution.DomainName
        EvaluateTargetHealth: false
  SecondaryDnsEntry:
    Type: "AWS::Route53::RecordSet"
    Condition: "SecondaryDnsEntry"
    Properties:
      HostedZoneId: !Sub "{{resolve:ssm:/route53/${InfrastructureName}/hosted-zone/id}}"
      Comment: "Secondary CloudFront DNS \"A ALIAS\" entry."
      Name: !Ref SecondaryDnsEntryName
      Type: "A"
      AliasTarget:
        HostedZoneId: !Ref CloudFrontHostedZoneId
        DNSName: !GetAtt Distribution.DomainName
        EvaluateTargetHealth: false
Outputs:
  DistributionId:
    Description: "The ID of the CloudFront distribution."
    Value: !Ref Distribution
    Export:
      Name: !Sub "${AWS::StackName}-DistributionId"
  DistributionDomainName:
    Description: "The domain name of the CloudFront distribution."
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-DistributionDomainName"
  PrimaryDnsEntry:
    Description: "The primary DNS entry."
    Value: !Ref PrimaryDnsEntry
    Export:
      Name: !Sub "${AWS::StackName}-PrimaryDnsEntry"
  SecondaryDnsEntry:
    Condition: "SecondaryDnsEntry"
    Description: "The secondary DNS entry."
    Value: !Ref SecondaryDnsEntry
    Export:
      Name: !Sub "${AWS::StackName}-SecondaryDnsEntry"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
      - AcmCertificateArn
    - Label:
        default: "DNS Configuration"
      Parameters:
      - PrimaryDnsEntryName
      - SecondaryDnsEntryName
      - CloudFrontHostedZoneId
    - Label:
        default: "General Distribution Configuration"
      Parameters:
      - DefaultOriginPath
      - DistributionComment
      - DistributionEnabled
      - DistributionIpv6Enabled
      - DistributionHttpVersion
      - DistributionDefaultRootObject
      - Distribution404PagePath
      - DistributionAllowedMethods
      - DistributionCachedMethods
      - DistributionCompress
      - DistributionSmoothStreaming
      - DistributionViewerProtocolPolicy
      - DistributionPriceClass
    - Label:
        default: "Defaults Caching TTL Configuration"
      Parameters:
      - DistributionErrorCachingMinTtl
      - DistributionMinimumTtl
      - DistributionMaximumTtl
      - DistributionDefaultTtl
    - Label:
        default: "Default Cache Policy Configuration"
      Parameters:
      - DefaultCachePolicyName
      - DefaultCookieBehavior
      - DefaultEnableAcceptEncodingBrotli
      - DefaultEnableAcceptEncodingGzip
      - DefaultHeaderBehavior
      - DefaultQueryStringBehavior
    - Label:
        default: "Individual Origin Configuration"
      Parameters:
      - OriginAccessIdentity
    - Label:
        default: "GEO Configuration"
      Parameters:
      - GeoRestrictionType
    - Label:
        default: "Secure Certificate Configuration"
      Parameters:
      - ViewerCertificateMinimumProtocolVersion
      - ViewerCertificateSslSupportMethod
    ParameterLabels:
      # Prerequisite Stacks or Services
      InfrastructureName:
        default: "Infrastructure Name:"
      AcmCertificateArn:
        default: "ACM Certificate ARN:"
      # DNS Configuration
      PrimaryDnsEntryName:
        default: "Primary DNS Entry:"
      SecondaryDnsEntryName:
        default: "Secondary DNS Entry:"
      CloudFrontHostedZoneId:
        default: "CloudFront Hosted Zone ID:"
      # General Distribution Configuration
      DefaultOriginPath:
        default: "Default Origin Path:"
      DistributionComment:
        default: "Comment:"
      DistributionEnabled:
        default: "Enable Distribution:"
      DistributionIpv6Enabled:
        default: "Enabled IPv6:"
      DistributionHttpVersion:
        default: "HTTP Version:"
      DistributionDefaultRootObject:
        default: "Default Root Object:"
      Distribution404PagePath:
        default: "Custom 404 Page:"
      DistributionAllowedMethods:
        default: "Allowed Methods:"
      DistributionCachedMethods:
        default: "Cache Methods:"
      DistributionCompress:
        default: "Compress Files:"
      DistributionSmoothStreaming:
        default: "Microsoft Smotth Streaming:"
      DistributionViewerProtocolPolicy:
        default: "Viewer Protocol Policy:"
      DistributionPriceClass:
        default: "Distribution Price Class:"
      # Distribution Caching TTL Defaults
      DistributionErrorCachingMinTtl:
        default: "Distribution Error Caching Minimum TTL:"
      DistributionMinimumTtl:
        default: "Distribution Minimum TTL:"
      DistributionMaximumTtl:
        default: "Distribution Maximum TTL:"
      DistributionDefaultTtl:
        default: "Distribution Default TTL:"
      # Default Cache Policy Configuration
      DefaultCachePolicyName:
        default: "Cache Policy Name:"
      DefaultCookieBehavior:
        default: "Cookie Behavior:"
      DefaultEnableAcceptEncodingBrotli:
        default: "Enable Accept Encoding Brotli:"
      DefaultEnableAcceptEncodingGzip:
        default: "Enable Accept Encoding GZIP:"
      DefaultHeaderBehavior:
        default: "Header Behavior:"
      DefaultQueryStringBehavior:
        default: "Query String Behavior:"
      # Individual Origin Configuration
      OriginAccessIdentity:
        default: "Origin Access Identity:"
      GeoRestrictionType:
        default: "GEO Restriction Type:"
      # Secure Certificate Configuration
      ViewerCertificateMinimumProtocolVersion:
        default: "Viewer Certificate Minimum Protocol Version:"
      ViewerCertificateSslSupportMethod:
        default: "Viewer Certificate SSL Support Method:"
