AWSTemplateFormatVersion: "2010-09-09" #The Format Version is optional.
Description: "Create an encrypted bucket for storing site content. (v1.0.1)"
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
    Default: "main"
  # Bucket Configuration
  BucketBaseName:
    Type: "String"
    Description: "The bucket base name."
  BucketObjectExpirationInDays:
    Type: "Number"
    Description: "The default age of certain objects before they are automatically deleted from the bucket."
    Default: 32
  IntelligentTieringTransitionInDays:
    Type: "Number"
    Description: "The days after object creation before the transition happens."
    Default: 0
  S3CanonicalUserId:
    Type: "String"
    Description: "The CloudFront origin access identity (OAI) for S3."
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub
      - "${InfrastructureName}-${ProductName}-${BucketBaseName}-${AWS::Region}"
      - ProductName: "{{resolve:ssm:/account/main/product/name}}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: "AES256"
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
            - "*"
            AllowedMethods:
            - "GET"
            - "HEAD"
            AllowedOrigins:
            - "*"
            Id: "AllowGet"
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
        - Id: "DefaultObjectMaxAge"
          Prefix: ""
          Status: "Enabled"
          AbortIncompleteMultipartUpload:
            DaysAfterInitiation: !Ref BucketObjectExpirationInDays
          NoncurrentVersionExpirationInDays: !Ref BucketObjectExpirationInDays
        - Id: "IntelligentTiering"
          Status: "Enabled"
          Transition:
            StorageClass: "INTELLIGENT_TIERING"
            TransitionInDays: !Ref IntelligentTieringTransitionInDays
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: "Suspended"
      Tags:
      - Key: "StackName"
        Value: !Ref "AWS::StackName"
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: !Ref Bucket
        Statement:
        - Sid: "CloudFrontAccess"
          Effect: "Allow"
          Principal:
            CanonicalUser: !Ref S3CanonicalUserId
          Action:
          - "s3:GetObject"
          Resource: !Sub "${Bucket.Arn}/*"
  # SSM Parameters
  ParamBucket:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description: "The bucket name."
      Name: !Sub "/s3/${InfrastructureName}/bucket/${BucketBaseName}/replicate/name"
      Tier: "Standard"
      Type: "String"
      Value: !Ref Bucket
      Tags:
        StackName: !Ref "AWS::StackName"
  ParamBucketArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description:  "The bucket ARN."
      Name: !Sub "/s3/${InfrastructureName}/bucket/${BucketBaseName}/replicate/arn"
      Tier: "Standard"
      Type: "String"
      Value: !GetAtt Bucket.Arn
      Tags:
        StackName: !Ref "AWS::StackName"
Outputs:
  Bucket:
    Description: "The bucket name."
    Value: !Ref Bucket
    Export:
      Name: !Sub "${AWS::StackName}-Bucket"
  BucketArn:
    Description: "The bucket ARN."
    Value: !GetAtt Bucket.Arn
    Export:
      Name: !Sub "${AWS::StackName}-BucketArn"
  BucketDomainName:
    Description: "The bucket domain name."
    Value: !GetAtt Bucket.DomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDomainName"
  BucketDualStackDomainName:
    Description: "The bucket dual-stack domain name."
    Value: !GetAtt Bucket.DualStackDomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketDualStackDomainName"
  BucketRegionalDomainName:
    Description: "The bucket regional domain name."
    Value: !GetAtt Bucket.RegionalDomainName
    Export:
      Name: !Sub "${AWS::StackName}-BucketRegionalDomainName"
  ParamBucket:
    Description: "The bucket name SSM Parameter."
    Value: !Ref ParamBucket
    Export:
      Name: !Sub "${AWS::StackName}-ParamBucket"
  ParamBucketArn:
    Description: "The ARN of bucket SSM Parameter."
    Value: !Ref ParamBucketArn
    Export:
      Name: !Sub "${AWS::StackName}-ParamBucketArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
    - Label:
        default: "Bucket Configuration"
      Parameters:
      - BucketBaseName
      - S3CanonicalUserId
    - Label:
        default: "LifeCycle Configuration"
      Parameters:
      - BucketObjectExpirationInDays
      - IntelligentTieringTransitionInDays
    ParameterLabels:
      # General Configuration
      InfrastructureName:
        default: "Infrastructure Name:"
      BucketBaseName:
        default: "Bucket Base Name:"
      S3CanonicalUserId:
        default: "S3 Canonical User ID:"
      BucketObjectExpirationInDays:
        default: "Bucket Object Expiration (In Days):"
      IntelligentTieringTransitionInDays:
        default: "Intelligent Tiering Transition (In Days):"
