AWSTemplateFormatVersion: "2010-09-09" #The Format Version is optional.
Description: "Create an ACM certificate with Route53 DNS validation (one subject alternative name) - (v1.0.2)."
Parameters:
  # General Configuration
  InfrastructureName:
    Type: "String"
    Description: "A name used to differentiate this infrastructure from other existing infrastructure."
  # Certificate Configuration
  PrimaryDomainName:
    Type: "String"
    Description: "Set the primary domain for this certificate (e.g. *.example.com)."
  ParamKey:
    Type: "String"
    Description: "A key to add to the SSM parameter name."
  SubjectAlternativeNamesList:
    Type: "CommaDelimitedList"
    Description: "Set a comma-delimited list of additional domains for this certificate (e.g. *.nonprod.example.com,*.prod.example.com)."
    Default: ""
  HostedZoneId:
    Type: "String"
    Description: "The Hosted Zone ID for the domain in Route53."
Resources:
  Certificate:
    Type: "AWS::CertificateManager::Certificate"
    Properties:
      CertificateTransparencyLoggingPreference: "ENABLED"
      DomainName: !Ref PrimaryDomainName
      SubjectAlternativeNames: !Ref SubjectAlternativeNamesList 
      ValidationMethod: "DNS"
      DomainValidationOptions:
      - DomainName: !Ref PrimaryDomainName
        HostedZoneId: !Ref HostedZoneId
      Tags:
      - Key: "StackName"
        Value: !Ref "AWS::StackName"
  # Secure Certificate Parameters
  ParamCertificateArn:
    Type: "AWS::SSM::Parameter"
    Properties:
      DataType: "text"
      Description: !Sub "The \"${InfrastructureName}\" \"${ParamKey}\" secure certificate ARN."
      Name: !Sub "/acm/${InfrastructureName}/certificate/${ParamKey}/arn"
      Tier: "Standard"
      Type: "String"
      Value: !Ref Certificate
      Tags:
        StackName: !Ref "AWS::StackName"
Outputs:
  CertificateArn:
    Description: "The ARN for the ACM certificate."
    Value: !Ref Certificate
    Export:
      Name: !Sub "${AWS::StackName}-CertificateArn"
  ParamCertificateArn:
    Description: "The ARN for the ACM certificate SSM parameter."
    Value: !Ref ParamCertificateArn
    Export:
      Name: !Sub "${AWS::StackName}-ParamCertificateArn"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: "General Configuration"
      Parameters:
      - InfrastructureName
    - Label:
        default: "Certificate Configuration"
      Parameters:
      - PrimaryDomainName
      - ParamKey
      - SubjectAlternativeNamesList
      - HostedZoneId
    ParameterLabels:
      # General Configuration
      InfrastructureName:
        default: "Infrastructure Name:"
      # Certificate Configuration
      PrimaryDomainName:
        default: "Primary Domain Name:"
      ParamKey:
        default: "Parameter Key:"
      SubjectAlternativeNamesList:
        default: "Subject Alternative Names List:"
      HostedZoneId:
        default: "Route53 Hosted Zone ID:"